algoritmo "Lista4_Ex39"
// Enunciado : 40. Efetuar a leitura de uma nota e, se o valor for
//maior ou igual a 50, imprimir na tela
//"APROVADO". Caso contrário mostrar na tela
//“REPROVADO”.

// Autor : Luis Vinicius Costa Silva
// Data : 04/04/2014
// Seção de Declarações 
var
n : real
inicio
escreva("Entre com a nota: ")
leia(n)
se n>=50 entao
escreval("APROVADO!")
senao
escreval("REPROVADO!")
fimse
fimalgoritmo
